### ISSUE TITLE
Deprecated selector in `atom-black-syntax/index.less`

### ISSUE THREAD

**Issue by the-code-innovator** [academicjargon/atom-black-syntax#2]
In `atom-black-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .fold-marker::before` => `atom-text-editor.editor .fold-marker::before`

* `atom-text-editor::shadow .editor .invisible-characters` => `atom-text-editor.editor .editor .invisible-characters`

* `atom-text-editor::shadow .line.cursor-line .fold-marker::after` => `atom-text-editor.editor .line.cursor-line .fold-marker::after`

* `atom-text-editor::shadow .line.cursor-line .fold-marker::before` => `atom-text-editor.editor .line.cursor-line .fold-marker::before`

* `atom-text-editor::shadow .cursor` => `atom-text-editor.editor .cursor`

* `atom-text-editor::shadow .bracket-matcher .region` => `atom-text-editor.editor .bracket-matcher .region`

* `atom-text-editor::shadow .cursor-line` => `atom-text-editor.editor .cursor-line`

* `atom-text-editor::shadow .line-number.foldable .icon-right` => `atom-text-editor.editor .line-number.foldable .icon-right`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by academicjargon** [comment]
fixed. I think.
