### ISSUE TITLE
Tab Indents Not Showing

### ISSUE THREAD

**Issue by VishwaJay** [academicjargon/atom-black-syntax#3]
**Describe the bug**
When entering a new line, the tab indents to not appear. This is especially frustrating where tabs are not merely pretty, but actually a part of the code (such as in SASS/SCSS).

**To Reproduce**
1. Enter some indented code.
2. Go to a new line.

**Expected behavior**
Tabs should be visible when the line is empty, rather than having to add work to make them visible.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Electron (atom client)
 - Version 1.38.0

**Additional context**
Please fix.

**Comment by academicjargon** [comment]
Added light green indentation marks.
